AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy GitHub Status Monitoring - Nuitka Binary Implementation'

Parameters:
  # ===== STANDARDIZED PARAMETERS FROM PARENT =====
  SaasAppName:
    Type: String
    Default: 'GitHub'
    Description: 'Name of the SaaS application'

  ApiUrl:
    Type: String
    Description: 'GitHub Status API endpoint URL'

  MonitoringSchedule:
    Type: String
    Description: 'Schedule expression for monitoring frequency'

  ApiKeysParameter:
    Type: String
    Description: 'ARN of the API keys parameter from parent stack'

  SharedLambdaRoleArn:
    Type: String
    Description: 'ARN of the shared Lambda execution role from parent stack'

  NotificationTopicArn:
    Type: String
    Description: 'ARN of the shared SNS topic for notifications'

  ParentStackName:
    Type: String
    Description: 'Name of the parent platform stack'

  BinaryDistributionUrl:
    Type: String
    Description: 'Base URL for Nuitka binary distribution'

  BinaryName:
    Type: String
    Default: 'watchy-github-monitor'
    Description: 'Name of the GitHub monitoring Nuitka binary'

  LogLevel:
    Type: String
    Default: 'INFO'
    Description: 'Log level for monitoring'

  TimeoutSeconds:
    Type: Number
    Default: 240
    Description: 'Timeout for monitoring operations'

  RetryAttempts:
    Type: Number
    Default: 3
    Description: 'Number of retry attempts'

Resources:
  # ===== GITHUB MONITORING LAMBDA =====
  GitHubMonitoringLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - x86_64
      Description: 'Watchy GitHub status monitoring with Nuitka native binary'
      FunctionName: !Sub '${ParentStackName}-GitHubMonitor'
      Runtime: python3.12
      Handler: index.lambda_handler
      Role: !Ref SharedLambdaRoleArn
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          # GitHub-specific configuration
          SAAS_APP_NAME: !Ref SaasAppName
          API_URL: !Ref ApiUrl
          CLOUDWATCH_NAMESPACE: !Sub 'Watchy/${SaasAppName}'
          
          # Platform configuration
          API_KEYS_PARAMETER: !Ref ApiKeysParameter
          NOTIFICATION_TOPIC_ARN: !Ref NotificationTopicArn
          
          # Binary configuration
          WATCHY_BINARY_DISTRIBUTION_URL: !Ref BinaryDistributionUrl
          WATCHY_BINARY_NAME: !Ref BinaryName
          
          # Runtime configuration
          WATCHY_LOG_LEVEL: !Ref LogLevel
          WATCHY_TIMEOUT_SECONDS: !Ref TimeoutSeconds
          WATCHY_RETRY_ATTEMPTS: !Ref RetryAttempts
          WATCHY_STACK_NAME: !Ref ParentStackName
      Code:
        ZipFile: |
          import json
          import subprocess
          import os
          import logging
          import urllib.request
          import time
          import hashlib
          import stat
          import boto3
          import gzip
          from datetime import datetime

          logger = logging.getLogger()
          logger.setLevel(getattr(logging, os.environ.get('WATCHY_LOG_LEVEL', 'INFO')))

          _binary_cache = {}

          def get_nuitka_binary_info():
              """Get GitHub Nuitka binary information"""
              try:
                  base_url = os.environ.get('WATCHY_BINARY_DISTRIBUTION_URL')
                  info_url = f"{base_url}/binaries/github-monitor/metadata.json"

                  with urllib.request.urlopen(info_url, timeout=10) as response:
                      if response.status == 200:
                          return json.loads(response.read().decode('utf-8'))
                  return None
              except Exception as e:
                  logger.error(f"Failed to get GitHub binary info: {e}")
                  return None

          def download_github_binary(binary_info):
              """Download GitHub monitoring Nuitka binary"""
              try:
                  binary_path = "/tmp/watchy-github-monitor"
                  
                  logger.info(f"Downloading GitHub Nuitka binary v{binary_info['version']}")
                  
                  with urllib.request.urlopen(binary_info['latestUrl'], timeout=120) as response:
                      if response.status != 200:
                          raise Exception(f"Download failed: HTTP {response.status}")
                      
                      if binary_info.get('compression') == 'gzip':
                          binary_data = gzip.decompress(response.read())
                      else:
                          binary_data = response.read()
                  
                  with open(binary_path, 'wb') as f:
                      f.write(binary_data)
                  
                  os.chmod(binary_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IROTH)
                  
                  # Verify checksum
                  if binary_info.get('sha256'):
                      actual_hash = hashlib.sha256(binary_data).hexdigest()
                      if actual_hash != binary_info['sha256']:
                          os.remove(binary_path)
                          raise Exception("GitHub binary checksum mismatch")
                  
                  logger.info("✅ GitHub Nuitka binary ready")
                  return binary_path
                  
              except Exception as e:
                  logger.error(f"GitHub binary download failed: {e}")
                  raise

          def lambda_handler(event, context):
              """GitHub monitoring handler with Nuitka binary"""
              start_time = time.time()
              
              try:
                  logger.info("🚀 Starting GitHub status monitoring...")
                  
                  # Get latest GitHub binary
                  binary_info = get_nuitka_binary_info()
                  if not binary_info:
                      raise Exception("Failed to get GitHub binary information")
                  
                  # Download GitHub binary
                  binary_path = download_github_binary(binary_info)
                  
                  # Load credentials
                  ssm = boto3.client('ssm')
                  
                  api_keys_response = ssm.get_parameter(
                      Name=os.environ.get('API_KEYS_PARAMETER'),
                      WithDecryption=True
                  )
                  api_keys = json.loads(api_keys_response['Parameter']['Value'])
                  
                  # Prepare environment for GitHub binary
                  env = os.environ.copy()
                  env['GITHUB_TOKEN'] = api_keys.get('github_token', '')
                  env['WATCHY_AWS_REQUEST_ID'] = context.aws_request_id
                  env['WATCHY_TIMESTAMP'] = str(int(time.time()))
                  
                  # Execute GitHub Nuitka binary
                  logger.info("⚡ Executing GitHub monitoring binary...")
                  result = subprocess.run(
                      [binary_path],
                      env=env,
                      capture_output=True,
                      text=True,
                      timeout=240
                  )
                  
                  if result.returncode != 0:
                      raise Exception(f"GitHub binary failed: {result.stderr}")
                  
                  # Parse results
                  try:
                      lines = [line.strip() for line in result.stdout.split('\n') if line.strip()]
                      for line in reversed(lines):
                          if line.startswith('{') and line.endswith('}'):
                              output_data = json.loads(line)
                              break
                      else:
                          output_data = {"message": "GitHub monitoring completed", "stdout": result.stdout}
                  except:
                      output_data = {"message": "GitHub monitoring completed", "stdout": result.stdout}
                  
                  # Add metadata
                  output_data.update({
                      'saas_app': 'GitHub',
                      'binary_type': binary_info.get('binary_type', 'nuitka'),
                      'binary_version': binary_info.get('version'),
                      'binary_sha256': binary_info.get('sha256'),
                      'binary_size': binary_info.get('binarySize'),
                      'build_time': binary_info.get('buildTime'),
                      'git_commit': binary_info.get('gitCommit'),
                      'build_number': binary_info.get('buildNumber'),
                      'target_platform': binary_info.get('target_platform'),
                      'lambda_compatible': binary_info.get('lambda_compatible'),
                      'execution_time': time.time() - start_time,
                      'timestamp': datetime.utcnow().isoformat()
                  })
                  
                  logger.info("✅ GitHub monitoring completed successfully")
                  
                  return {
                      'statusCode': 200,
                      'body': json.dumps(output_data)
                  }
                  
              except Exception as e:
                  error_msg = f"GitHub monitoring failed: {str(e)}"
                  logger.error(f"❌ {error_msg}")
                  
                  return {
                      'statusCode': 500,
                      'body': json.dumps({
                          'error': error_msg,
                          'saas_app': 'GitHub',
                          'execution_time': time.time() - start_time
                      })
                  }

  # ===== GITHUB MONITORING SCHEDULE =====
  GitHubScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${ParentStackName}-GitHubSchedule'
      Description: 'Schedule for GitHub status monitoring'
      ScheduleExpression: !Ref MonitoringSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt GitHubMonitoringLambda.Arn
          Id: GitHubMonitoringTarget

  GitHubLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GitHubMonitoringLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GitHubScheduleRule.Arn

  # ===== GITHUB CLOUDWATCH RESOURCES =====
  GitHubLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${GitHubMonitoringLambda}'
      RetentionInDays: 30

  # GitHub Service Alarms
  GitHubAPIResponseAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-APIResponse'
      AlarmDescription: 'GitHub Status API response monitoring'
      MetricName: APIResponse
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 200
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: breaching
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubGitOperationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-GitOperations'
      AlarmDescription: 'GitHub Git Operations service status'
      MetricName: GitOperations
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubAPIRequestsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-APIRequests'
      AlarmDescription: 'GitHub API Requests service status'
      MetricName: APIRequests
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubWebhooksAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-Webhooks'
      AlarmDescription: 'GitHub Webhooks service status'
      MetricName: Webhooks
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubActionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-Actions'
      AlarmDescription: 'GitHub Actions service status'
      MetricName: Actions
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubPackagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-Packages'
      AlarmDescription: 'GitHub Packages service status'
      MetricName: Packages
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

  GitHubPagesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ParentStackName}-GitHub-Pages'
      AlarmDescription: 'GitHub Pages service status'
      MetricName: Pages
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: ignore
      AlarmActions:
        - !Ref NotificationTopicArn

Outputs:
  LambdaFunctionName:
    Description: 'GitHub monitoring Lambda function name'
    Value: !Ref GitHubMonitoringLambda

  LambdaFunctionArn:
    Description: 'GitHub monitoring Lambda function ARN'
    Value: !GetAtt GitHubMonitoringLambda.Arn

  APIResponseAlarm:
    Description: 'GitHub API Response alarm ARN'
    Value: !GetAtt GitHubAPIResponseAlarm.Arn

  GitOperationsAlarm:
    Description: 'GitHub Git Operations alarm ARN'
    Value: !GetAtt GitHubGitOperationsAlarm.Arn

  APIRequestsAlarm:
    Description: 'GitHub API Requests alarm ARN'
    Value: !GetAtt GitHubAPIRequestsAlarm.Arn

  WebhooksAlarm:
    Description: 'GitHub Webhooks alarm ARN'
    Value: !GetAtt GitHubWebhooksAlarm.Arn

  ActionsAlarm:
    Description: 'GitHub Actions alarm ARN'
    Value: !GetAtt GitHubActionsAlarm.Arn

  PackagesAlarm:
    Description: 'GitHub Packages alarm ARN'
    Value: !GetAtt GitHubPackagesAlarm.Arn

  PagesAlarm:
    Description: 'GitHub Pages alarm ARN'
    Value: !GetAtt GitHubPagesAlarm.Arn
