---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy GitHub Monitoring - Nested Stack v1.0.0'

Metadata:
  Version: '1.0.0'
  LastUpdated: '2026-02-01'

Parameters:
  # ===== INHERITED FROM PARENT STACK =====
  SaasAppName:
    Type: String
    Default: 'GitHub'
    Description: 'Name of the SaaS application being monitored'

  ApiUrl:
    Type: String
    Default: 'https://www.githubstatus.com/api/v2/incidents/unresolved.json'
    Description: 'GitHub Status API endpoint URL for unresolved incidents'

  MonitoringSchedule:
    Type: String
    Default: 'rate(5 minutes)'
    Description: 'Schedule expression for monitoring frequency'

  TimeoutSeconds:
    Type: Number
    Default: 240
    Description: 'Lambda function timeout in seconds'

  RetryAttempts:
    Type: Number
    Default: 3
    Description: 'Number of retry attempts for failed API calls'

  LogLevel:
    Type: String
    Default: 'INFO'
    Description: 'Log level for monitoring function'

  SharedLambdaRoleArn:
    Type: String
    Description: 'ARN of the shared Lambda execution role from parent stack'

  NotificationTopicArn:
    Type: String
    Description: >-
      ARN of the shared SNS topic for notifications from parent stack

  ParentStackName:
    Type: String
    Description: 'Name of the parent platform stack'

  S3BucketName:
    Type: String
    Default: 'watchy-resources'
    Description: 'S3 bucket containing Lambda packages'

Resources:
  # ===== CLOUDWATCH LOG GROUPS =====
  GitHubIncidentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /watchy/services/github
      RetentionInDays: 30

  GitHubLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/watchy-github-monitor
      RetentionInDays: 7

  # ===== GITHUB MONITORING LAMBDA =====
  GitHubMonitoringLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - GitHubLambdaLogGroup
    Properties:
      Architectures:
        - arm64
      Description: >-
        Watchy GitHub incident monitoring
      FunctionName: watchy-github-monitor
      Runtime: python3.14
      Handler: lambda_function.lambda_handler
      Role: !Ref SharedLambdaRoleArn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          # GitHub-specific configuration
          SAAS_APP_NAME: !Ref SaasAppName
          API_URL: !Ref ApiUrl
          CLOUDWATCH_NAMESPACE: !Sub 'Watchy/${SaasAppName}'
          CLOUDWATCH_LOG_GROUP: '/watchy/services/github'
          POLLING_INTERVAL_MINUTES: '5'

          # Platform configuration
          NOTIFICATION_TOPIC_ARN: !Ref NotificationTopicArn

          # Runtime configuration
          WATCHY_LOG_LEVEL: !Ref LogLevel
          WATCHY_TIMEOUT_SECONDS: !Ref TimeoutSeconds
          WATCHY_RETRY_ATTEMPTS: !Ref RetryAttempts
          WATCHY_STACK_NAME: !Ref ParentStackName

          # Version information (set during deployment)
          LAMBDA_VERSION: '1.0.0'
          BUILD_DATE: !Sub '${AWS::StackName}-${AWS::Region}'
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: 'github-monitor.zip'

  # ===== GITHUB MONITORING SCHEDULE =====
  GitHubScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: watchy-github-schedule
      Description: 'Schedule for GitHub incident monitoring'
      ScheduleExpression: !Ref MonitoringSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt GitHubMonitoringLambda.Arn
          Id: GitHubMonitoringTarget

  GitHubLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt GitHubMonitoringLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GitHubScheduleRule.Arn

  # ===== GITHUB CLOUDWATCH ALARMS =====

  # API Response Alarm
  GitHubAPIResponseAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: watchy-github-api-response
      AlarmDescription: 'GitHub Status API response monitoring'
      MetricName: APIResponse
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 200
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: breaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # Total Unresolved Incidents Alarm
  GitHubTotalIncidentsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-GitHub-TotalIncidents-${AWS::Region}'
      AlarmDescription: >-
        GitHub Total Unresolved Incidents - alerts when any incidents are present
      MetricName: TotalUnresolvedIncidents
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # Major Incidents Alarm
  GitHubMajorIncidentsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-GitHub-MajorIncidents-${AWS::Region}'
      AlarmDescription: >-
        GitHub Major Impact Incidents - alerts on major severity incidents
      MetricName: IncidentsMajor
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # Critical Incidents Alarm
  GitHubCriticalIncidentsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-GitHub-CriticalIncidents-${AWS::Region}'
      AlarmDescription: >-
        GitHub Critical Impact Incidents - alerts on critical severity incidents
      MetricName: IncidentsCritical
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # Highest Impact Level Alarm (for overall severity alerting)
  GitHubHighestImpactAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-GitHub-HighestImpact-${AWS::Region}'
      AlarmDescription: >-
        GitHub Highest Impact Level - alerts when impact level is major (2) or critical (3)
      MetricName: HighestImpactLevel
      Namespace: Watchy/GitHub
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # ===== CLOUDWATCH DASHBOARD =====
  GitHubMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: watchy-github
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "Watchy/GitHub", "TotalUnresolvedIncidents" ],
                  [ ".", "IncidentsMinor" ],
                  [ ".", "IncidentsMajor" ],
                  [ ".", "IncidentsCritical" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "GitHub Incident Status",
                "period": 300,
                "stat": "Average"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 6,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "Watchy/GitHub", "APIResponse" ]
                ],
                "view": "singleValue",
                "region": "${AWS::Region}",
                "title": "API Response Code",
                "period": 300,
                "stat": "Average"
              }
            }
          ]
        }

Outputs:
  LambdaFunctionName:
    Description: 'GitHub monitoring Lambda function name'
    Value: !Ref GitHubMonitoringLambda

  LambdaFunctionArn:
    Description: 'GitHub monitoring Lambda function ARN'
    Value: !GetAtt GitHubMonitoringLambda.Arn

  IncidentLogGroup:
    Description: 'CloudWatch Log Group for GitHub incidents'
    Value: !Ref GitHubIncidentLogGroup

  LambdaLogGroup:
    Description: 'CloudWatch Log Group for Lambda execution logs'
    Value: !Ref GitHubLambdaLogGroup

  APIResponseAlarm:
    Description: 'GitHub API Response alarm ARN'
    Value: !GetAtt GitHubAPIResponseAlarm.Arn

  TotalIncidentsAlarm:
    Description: 'GitHub Total Incidents alarm ARN'
    Value: !GetAtt GitHubTotalIncidentsAlarm.Arn

  MajorIncidentsAlarm:
    Description: 'GitHub Major Incidents alarm ARN'
    Value: !GetAtt GitHubMajorIncidentsAlarm.Arn

  CriticalIncidentsAlarm:
    Description: 'GitHub Critical Incidents alarm ARN'
    Value: !GetAtt GitHubCriticalIncidentsAlarm.Arn

  HighestImpactAlarm:
    Description: 'GitHub Highest Impact Level alarm ARN'
    Value: !GetAtt GitHubHighestImpactAlarm.Arn

  DashboardName:
    Description: 'CloudWatch Dashboard name for GitHub monitoring'
    Value: !Ref GitHubMonitoringDashboard

  DashboardURL:
    Description: 'CloudWatch Dashboard URL'
    Value: !Sub >-
      https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${GitHubMonitoringDashboard}
