AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy Monitoring Platform v5.4.0'
Metadata:
  Version: '5.4.0'
  LastUpdated: '2025-10-18'
  RecommendedStackName: 'Watchy'
  Changelog:
    - Added CloudWatch Log Groups as CloudFormation resources (prevents dashboard errors)
    - Incident log group with 30-day retention, Lambda log group with 7-day retention
    - Added CloudWatch Dashboard for comprehensive Slack service visualization
    - Dashboard includes time series charts, single value metrics, and log insights
    - Updated Slack monitoring alarms to cover all 11 Slack services
    - Standardized alarm naming to Watchy-Slack-<ServiceName> format
    - Set alarm thresholds to alert on incident (2) and outage (3) severity levels
    - Added comprehensive alarm coverage for Login/SSO, Messaging, Notifications, Search, Workspace/Org Administration, Canvases, Connectivity, Files, Huddles, Apps/Integrations/APIs, and Workflows

Parameters:
  # ===== GLOBAL CONFIGURATION =====
  NotificationEmail:
    Type: String
    Description: 'Email address for CloudWatch alarm notifications sent via Simple Notification Service (SNS)'
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: 'Must be a valid email address'

  MonitoringSchedule:
    Type: String
    Default: 'rate(5 minutes)'
    Description: 'Watchy monitoring poll interval'

  TimeoutSeconds:
    Type: Number
    Default: 240
    MinValue: 30
    MaxValue: 900
    Description: 'Timeout in seconds for Watchy monitoring operations'

  RetryAttempts:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
    Description: 'Number of retry attempts for failed Watchy operations'

Resources:
  # ===== SHARED PLATFORM RESOURCES =====
  
  # Shared SNS Topic for All SaaS Monitoring Alerts
  WatchyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub 'Watchy-Alerts-${AWS::Region}'
      DisplayName: !Sub 'Watchy Alerts (${AWS::Region})'
      Tags:
        - Key: Project
          Value: Watchy
        - Key: Component
          Value: Notifications
        - Key: StackName
          Value: !Ref AWS::StackName

  # Email Subscription to SNS Topic
  WatchyEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WatchyNotificationTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # Shared IAM Role for All Lambda Functions
  WatchySharedLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-WatchyPlatformRole-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub 'WatchyPlatformPolicy-${AWS::Region}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudWatch Metrics for all SaaS apps
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              # CloudWatch Logs with Watchy namespace
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*Watchy*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/watchy/slack/*'
              # SNS Publish for custom notifications
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref WatchyNotificationTopic

  # ===== SLACK MONITORING STACK =====

  # Slack Monitoring Stack
  SlackMonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/watchy-resources-prod/customer-templates/templates/watchy-slack-monitoring.yaml'
      Parameters:
        SaasAppName: 'Slack'
        ApiUrl: 'https://status.slack.com/api/v2.0.0/current'
        MonitoringSchedule: !Ref MonitoringSchedule
        TimeoutSeconds: !Ref TimeoutSeconds
        RetryAttempts: !Ref RetryAttempts
        SharedLambdaRoleArn: !GetAtt WatchySharedLambdaRole.Arn
        NotificationTopicArn: !Ref WatchyNotificationTopic
        ParentStackName: !Ref AWS::StackName
        BinaryDistributionUrl: 'https://releases.watchy.cloud'
        BinaryName: 'watchy-slack-monitor'
      Tags:
        - Key: Project
          Value: Watchy
        - Key: SaasApp
          Value: Slack
        - Key: BinaryType
          Value: Nuitka
        - Key: ParentStack
          Value: !Ref AWS::StackName

Outputs:
  # ===== SHARED PLATFORM OUTPUTS =====
  NotificationTopicArn:
    Description: 'ARN of the shared SNS topic for Watchy monitoring alerts'
    Value: !Ref WatchyNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  SharedLambdaRoleArn:
    Description: 'ARN of the shared Lambda execution role for Watchy monitoring'
    Value: !GetAtt WatchySharedLambdaRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SharedLambdaRole'

  NotificationEmail:
    Description: 'Email address configured for platform notifications'
    Value: !Ref NotificationEmail

  # ===== SLACK MONITORING OUTPUT =====
  SlackMonitoringStackId:
    Description: 'Stack ID of the Slack monitoring nested stack'
    Value: !Ref SlackMonitoringStack

  # ===== PLATFORM SUMMARY =====
  PlatformVersion:
    Description: 'Watchy platform version'
    Value: '5.1.0-modular'

  BinaryDistributionUrl:
    Description: 'Base URL for binary distribution'
    Value: 'https://releases.watchy.cloud'
