---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy Slack Monitoring - Nested Stack v1.0.0'

Metadata:
  Version: '1.0.0'
  LastUpdated: '2025-01-25'

Parameters:
  # ===== INHERITED FROM PARENT STACK =====
  SaasAppName:
    Type: String
    Default: 'Slack'
    Description: 'Name of the SaaS application being monitored'

  ApiUrl:
    Type: String
    Default: 'https://status.slack.com/api/v2.0.0/current'
    Description: 'Slack Status API endpoint URL'

  MonitoringSchedule:
    Type: String
    Default: 'rate(5 minutes)'
    Description: 'Schedule expression for monitoring frequency'

  TimeoutSeconds:
    Type: Number
    Default: 240
    Description: 'Lambda function timeout in seconds'

  RetryAttempts:
    Type: Number
    Default: 3
    Description: 'Number of retry attempts for failed API calls'

  LogLevel:
    Type: String
    Default: 'INFO'
    Description: 'Log level for monitoring function'

  SharedLambdaRoleArn:
    Type: String
    Description: 'ARN of the shared Lambda execution role from parent stack'

  NotificationTopicArn:
    Type: String
    Description: >-
      ARN of the shared SNS topic for notifications from parent stack

  ParentStackName:
    Type: String
    Description: 'Name of the parent platform stack'

  S3BucketName:
    Type: String
    Default: 'watchy-resources'
    Description: 'S3 bucket containing Lambda packages'

Resources:
  # ===== CLOUDWATCH LOG GROUPS =====
  SlackIncidentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /watchy/services/slack
      RetentionInDays: 30

  SlackLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/watchy-slack-monitor
      RetentionInDays: 7

  # ===== SLACK MONITORING LAMBDA =====
  SlackMonitoringLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - SlackLambdaLogGroup
    Properties:
      Architectures:
        - arm64
      Description: >-
        Watchy Slack status monitoring
      FunctionName: watchy-slack-monitor
      Runtime: python3.14
      Handler: lambda_function.lambda_handler
      Role: !Ref SharedLambdaRoleArn
      Timeout: 300
      MemorySize: 256
      Environment:
        Variables:
          # Slack-specific configuration
          SAAS_APP_NAME: !Ref SaasAppName
          API_URL: !Ref ApiUrl
          CLOUDWATCH_NAMESPACE: !Sub 'Watchy/${SaasAppName}'
          CLOUDWATCH_LOG_GROUP: '/watchy/services/slack'
          POLLING_INTERVAL_MINUTES: '5'

          # Platform configuration
          NOTIFICATION_TOPIC_ARN: !Ref NotificationTopicArn

          # Runtime configuration
          WATCHY_LOG_LEVEL: !Ref LogLevel
          WATCHY_TIMEOUT_SECONDS: !Ref TimeoutSeconds
          WATCHY_RETRY_ATTEMPTS: !Ref RetryAttempts
          WATCHY_STACK_NAME: !Ref ParentStackName

          # Version information (set during deployment)
          LAMBDA_VERSION: '1.0.0'
          BUILD_DATE: !Sub '${AWS::StackName}-${AWS::Region}'
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: 'slack-monitor.zip'

  # ===== SLACK MONITORING SCHEDULE =====
  SlackScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: watchy-slack-schedule
      Description: 'Schedule for Slack status monitoring'
      ScheduleExpression: !Ref MonitoringSchedule
      State: ENABLED
      Targets:
        - Arn: !GetAtt SlackMonitoringLambda.Arn
          Id: SlackMonitoringTarget

  SlackLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt SlackMonitoringLambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SlackScheduleRule.Arn

  # ===== SLACK CLOUDWATCH ALARMS =====
  # Slack Service Alarms
  SlackAPIResponseAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: watchy-slack-api-response
      AlarmDescription: 'Slack Status API response monitoring'
      MetricName: APIResponse
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 200
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: breaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackLoginSSOAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: watchy-slack-login-sso
      AlarmDescription: >-
        Slack Login/SSO service - alerts on incident (2) and outage (3)
      MetricName: LoginSSO
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackMessagingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Messaging-${AWS::Region}'
      AlarmDescription: >-
        Slack Messaging service - alerts on incident (2) and outage (3)
      MetricName: Messaging
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackNotificationsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Notifications-${AWS::Region}'
      AlarmDescription: >-
        Slack Notifications service - alerts on incident (2) and outage (3)
      MetricName: Notifications
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackSearchAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Search-${AWS::Region}'
      AlarmDescription: >-
        Slack Search service - alerts on incident (2) and outage (3)
      MetricName: Search
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackWorkspaceOrgAdministrationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-WorkspaceAdmin-${AWS::Region}'
      AlarmDescription: >-
        Slack Workspace/Org Administration service - alerts on incident (2)
        and outage (3)
      MetricName: WorkspaceOrgAdministration
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackCanvasesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Canvases-${AWS::Region}'
      AlarmDescription: >-
        Slack Canvases service - alerts on incident (2) and outage (3)
      MetricName: Canvases
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackConnectivityAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Connectivity-${AWS::Region}'
      AlarmDescription: >-
        Slack Connectivity service - alerts on incident (2) and outage (3)
      MetricName: Connectivity
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackFilesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Files-${AWS::Region}'
      AlarmDescription: >-
        Slack Files service - alerts on incident (2) and outage (3)
      MetricName: Files
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackHuddlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Huddles-${AWS::Region}'
      AlarmDescription: >-
        Slack Huddles service - alerts on incident (2) and outage (3)
      MetricName: Huddles
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackAppsIntegrationsAPIsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-AppsAPIs-${AWS::Region}'
      AlarmDescription: >-
        Slack Apps/Integrations/APIs service - alerts on incident (2)
        and outage (3)
      MetricName: AppsIntegrationsAPIs
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  SlackWorkflowsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'Watchy-Slack-Workflows-${AWS::Region}'
      AlarmDescription: >-
        Slack Workflows service - alerts on incident (2) and outage (3)
      MetricName: Workflows
      Namespace: Watchy/Slack
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref NotificationTopicArn

  # ===== CLOUDWATCH DASHBOARD =====
  SlackMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: watchy-slack
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "Watchy/Slack", "LoginSSO" ],
                  [ ".", "Messaging" ],
                  [ ".", "Notifications" ],
                  [ ".", "Search" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Slack Service Health Status",
                "period": 300,
                "stat": "Average"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 6,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "Watchy/Slack", "APIResponse" ]
                ],
                "view": "singleValue",
                "region": "${AWS::Region}",
                "title": "API Response Code",
                "period": 300,
                "stat": "Average"
              }
            }
          ]
        }

Outputs:
  LambdaFunctionName:
    Description: 'Slack monitoring Lambda function name'
    Value: !Ref SlackMonitoringLambda

  LambdaFunctionArn:
    Description: 'Slack monitoring Lambda function ARN'
    Value: !GetAtt SlackMonitoringLambda.Arn

  IncidentLogGroup:
    Description: 'CloudWatch Log Group for Slack incidents'
    Value: !Ref SlackIncidentLogGroup

  LambdaLogGroup:
    Description: 'CloudWatch Log Group for Lambda execution logs'
    Value: !Ref SlackLambdaLogGroup

  APIResponseAlarm:
    Description: 'Slack API Response alarm ARN'
    Value: !GetAtt SlackAPIResponseAlarm.Arn

  LoginSSOAlarm:
    Description: 'Slack Login/SSO alarm ARN'
    Value: !GetAtt SlackLoginSSOAlarm.Arn

  MessagingAlarm:
    Description: 'Slack Messaging alarm ARN'
    Value: !GetAtt SlackMessagingAlarm.Arn

  NotificationsAlarm:
    Description: 'Slack Notifications alarm ARN'
    Value: !GetAtt SlackNotificationsAlarm.Arn

  SearchAlarm:
    Description: 'Slack Search alarm ARN'
    Value: !GetAtt SlackSearchAlarm.Arn

  WorkspaceOrgAdministrationAlarm:
    Description: 'Slack Workspace/Org Administration alarm ARN'
    Value: !GetAtt SlackWorkspaceOrgAdministrationAlarm.Arn

  CanvasesAlarm:
    Description: 'Slack Canvases alarm ARN'
    Value: !GetAtt SlackCanvasesAlarm.Arn

  ConnectivityAlarm:
    Description: 'Slack Connectivity alarm ARN'
    Value: !GetAtt SlackConnectivityAlarm.Arn

  FilesAlarm:
    Description: 'Slack Files alarm ARN'
    Value: !GetAtt SlackFilesAlarm.Arn

  HuddlesAlarm:
    Description: 'Slack Huddles alarm ARN'
    Value: !GetAtt SlackHuddlesAlarm.Arn

  AppsIntegrationsAPIsAlarm:
    Description: 'Slack Apps/Integrations/APIs alarm ARN'
    Value: !GetAtt SlackAppsIntegrationsAPIsAlarm.Arn

  WorkflowsAlarm:
    Description: 'Slack Workflows alarm ARN'
    Value: !GetAtt SlackWorkflowsAlarm.Arn

  DashboardName:
    Description: 'CloudWatch Dashboard name for Slack monitoring'
    Value: !Ref SlackMonitoringDashboard

  DashboardURL:
    Description: 'CloudWatch Dashboard URL'
    Value: !Sub >-
      https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${SlackMonitoringDashboard}
