AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy parent template with nested Slack monitoring stack'

Metadata:
  Version: '3.0.0'
  LastUpdated: '2025-07-20'
  Changelog:
    - Nested stack architecture with centralized license management
    - Parent stack manages license parameter only
    - Child stack contains all Slack monitoring resources

Parameters:
  SlackStatusApiUrl:
    Type: String
    Default: 'https://status.slack.com/api/v2.0.0/current'
    Description: 'Slack Status API endpoint URL'
  
  MonitoringSchedule:
    Type: String
    Default: 'rate(5 minutes)'
    Description: 'Schedule expression for monitoring frequency'
  
  WatchyLicenseKey:
    Type: String
    NoEcho: true
    Description: '(Optional) Watchy license key for binary authentication'
    MinLength: 10
    ConstraintDescription: 'License key must be at least 10 characters long'

  NestedStackTemplateUrl:
    Type: String
    Description: 'S3 URL for the nested Slack monitoring stack template'
    Default: 'https://watchy-resources.s3.us-west-2.amazonaws.com/cloudformation/watchy-nested-slack.yaml'

  NotificationEmail:
    Type: String
    Description: 'Email address for CloudWatch alarm notifications'
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: 'Must be a valid email address'

Resources:
  # Parameter Store for Watchy License Key (only resource in parent stack)
  WatchyLicenseParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${AWS::StackName}/watchy/license-key'
      Type: String
      Value: !Ref WatchyLicenseKey
      Description: 'Watchy license key for binary authentication'
      Tier: Standard
      Tags:
        Project: Watchy
        Component: SlackStatus
        StackName: !Ref AWS::StackName

  # SNS Topic for CloudWatch Alarm Notifications
  WatchyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-WatchyAlerts'
      DisplayName: !Sub 'Watchy Alerts - ${AWS::StackName}'
      Tags:
        - Key: Project
          Value: Watchy
        - Key: Component
          Value: Notifications
        - Key: StackName
          Value: !Ref AWS::StackName

  # Email Subscription to SNS Topic
  WatchyEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WatchyNotificationTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # Nested Stack for Slack Monitoring Resources
  SlackMonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref NestedStackTemplateUrl
      Parameters:
        SlackStatusApiUrl: !Ref SlackStatusApiUrl
        MonitoringSchedule: !Ref MonitoringSchedule
        LogLevel: 'INFO'
        TimeoutSeconds: 240
        RetryAttempts: 3
        WatchyLicenseParameter: !Ref WatchyLicenseParameter
        ParentStackName: !Ref AWS::StackName
      Tags:
        - Key: Project
          Value: Watchy
        - Key: Component
          Value: SlackMonitoring
        - Key: ParentStack
          Value: !Ref AWS::StackName

Outputs:
  LicenseParameterName:
    Description: 'Parameter Store name for license key'
    Value: !Ref WatchyLicenseParameter
    Export:
      Name: !Sub '${AWS::StackName}-LicenseParameter'

  # SNS Topic for Alarm Notifications
  NotificationTopicArn:
    Description: 'ARN of the SNS topic for CloudWatch alarm notifications'
    Value: !Ref WatchyNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  NotificationTopicName:
    Description: 'Name of the SNS topic for CloudWatch alarm notifications'
    Value: !GetAtt WatchyNotificationTopic.TopicName

  NotificationEmail:
    Description: 'Email address configured for notifications'
    Value: !Ref NotificationEmail

  # Nested Stack Outputs (passed through from child stack)
  LambdaFunctionName:
    Description: 'Lambda function name from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.LambdaFunctionName
  
  BinaryChannel:
    Description: 'Binary channel (always latest) from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.BinaryChannel
  
  APIResponseAlarm:
    Description: 'ARN of the API Response alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.APIResponseAlarm
    Export:
      Name: !Sub '${AWS::StackName}-APIResponseAlarm'

  AppsIntegrationsAPIsAlarm:
    Description: 'ARN of the Apps/Integrations/APIs alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.AppsIntegrationsAPIsAlarm
    Export:
      Name: !Sub '${AWS::StackName}-AppsIntegrationsAPIsAlarm'

  CanvasesAlarm:
    Description: 'ARN of the Canvases alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.CanvasesAlarm
    Export:
      Name: !Sub '${AWS::StackName}-CanvasesAlarm'

  ConnectivityAlarm:
    Description: 'ARN of the Connectivity alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.ConnectivityAlarm
    Export:
      Name: !Sub '${AWS::StackName}-ConnectivityAlarm'

  FilesAlarm:
    Description: 'ARN of the Files alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.FilesAlarm
    Export:
      Name: !Sub '${AWS::StackName}-FilesAlarm'

  HuddlesAlarm:
    Description: 'ARN of the Huddles alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.HuddlesAlarm
    Export:
      Name: !Sub '${AWS::StackName}-HuddlesAlarm'

  LoginSSOAlarm:
    Description: 'ARN of the Login/SSO alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.LoginSSOAlarm
    Export:
      Name: !Sub '${AWS::StackName}-LoginSSOAlarm'

  MessagingAlarm:
    Description: 'ARN of the Messaging alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.MessagingAlarm
    Export:
      Name: !Sub '${AWS::StackName}-MessagingAlarm'

  NotificationsAlarm:
    Description: 'ARN of the Notifications alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.NotificationsAlarm
    Export:
      Name: !Sub '${AWS::StackName}-NotificationsAlarm'

  SearchAlarm:
    Description: 'ARN of the Search alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.SearchAlarm
    Export:
      Name: !Sub '${AWS::StackName}-SearchAlarm'

  WorkflowsAlarm:
    Description: 'ARN of the Workflows alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.WorkflowsAlarm
    Export:
      Name: !Sub '${AWS::StackName}-WorkflowsAlarm'

  WorkspaceOrgAdministrationAlarm:
    Description: 'ARN of the Workspace/OrgAdministration alarm from nested stack'
    Value: !GetAtt SlackMonitoringStack.Outputs.WorkspaceOrgAdministrationAlarm
    Export:
      Name: !Sub '${AWS::StackName}-WorkspaceOrgAdministrationAlarm'