---
name: Feature Request
description: Suggest a new feature for Watchy Open Source
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Thank you for suggesting a new feature for Watchy Open Source!
        We appreciate community contributions and ideas.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you'd like to request
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New SaaS Integration (GitHub, Zoom, etc.)
        - CloudWatch Enhancement
        - Alerting/Notification Improvement
        - Dashboard/Visualization
        - Configuration/Parameter
        - Documentation
        - Developer Experience
        - Performance Optimization
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What alternatives have you considered?

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how this could be implemented, please share
      placeholder: |
        Do you have any ideas on how this feature could be implemented?
        Are you willing to contribute to the implementation?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation
        - label: I can provide use case examples

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable
      placeholder: |
        Provide specific examples of how this feature would be used:
        1. Use case 1...
        2. Use case 2...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context or screenshots about the feature request
      placeholder: Add any other context or screenshots about the feature request here
