AWSTemplateFormatVersion: '2010-09-09'
Description: 'Watchy Slack Monitoring Platform - Simplified Slack-Only Architecture with Nuitka Binaries'

Metadata:
  Version: '5.0.0'
  LastUpdated: '2025-08-31'
  Changelog:
    - Simplified to Slack-only monitoring platform
    - Centralized shared resources (IAM, SNS, Parameter Store)
    - Nuitka native binary compilation approach
    - Focused single-SaaS design for Slack monitoring

Parameters:
  # ===== GLOBAL CONFIGURATION =====
  NotificationEmail:
    Type: String
    Default: 'contact@watchy.cloud'
    Description: 'Email address for CloudWatch alarm notifications for Slack monitoring'
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: 'Must be a valid email address'

  MonitoringSchedule:
    Type: String
    Default: 'rate(5 minutes)'
    Description: 'Monitoring frequency for Slack status checks'

  LogLevel:
    Type: String
    Default: 'INFO'
    AllowedValues: ['DEBUG', 'INFO', 'WARN', 'ERROR']
    Description: 'Log level for Slack monitoring binary'

  TimeoutSeconds:
    Type: Number
    Default: 240
    MinValue: 30
    MaxValue: 900
    Description: 'Timeout in seconds for Slack monitoring operations'

  RetryAttempts:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
    Description: 'Number of retry attempts for failed Slack operations'

  # ===== TEMPLATE CONFIGURATION =====
  TemplateBaseUrl:
    Type: String
    Default: "https://s3.amazonaws.com/watchy-resources-prod/customer-templates/templates"
    Description: "Base URL for CloudFormation templates"

  BinaryDistributionUrl:
    Type: String
    Default: 'https://releases.watchy.cloud'
    Description: 'Base URL for Nuitka binary distribution (CloudFront CDN)'

  # ===== SLACK-SPECIFIC API ENDPOINT =====
  SlackApiUrl:
    Type: String
    Default: 'https://status.slack.com/api/v2.0.0/current'
    Description: 'Slack Status API endpoint'

Resources:
  # ===== SHARED PLATFORM RESOURCES =====
  
  # API Keys Parameter Store (JSON format for multiple SaaS APIs)
  # Note: Using String type for CloudFormation compatibility.
  # For production, consider using AWS Secrets Manager for API keys.
  ApiKeysParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${AWS::StackName}/watchy/api-keys'
      Type: String
      Value: |
        {
          "github_token": "PLACEHOLDER_GITHUB_TOKEN",
          "zoom_api_key": "PLACEHOLDER_ZOOM_API_KEY",
          "zoom_api_secret": "PLACEHOLDER_ZOOM_API_SECRET",
          "slack_oauth_token": "PLACEHOLDER_SLACK_TOKEN",
          "custom_webhooks": {
            "slack": "PLACEHOLDER_SLACK_WEBHOOK",
            "teams": "PLACEHOLDER_TEAMS_WEBHOOK"
          }
        }
      Description: 'API keys and secrets for SaaS integrations (JSON format)'
      Tags:
        Project: Watchy
        Component: ApiKeys
        StackName: !Ref AWS::StackName

  # Shared SNS Topic for All SaaS Monitoring Alerts
  WatchyNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-WatchyPlatformAlerts'
      DisplayName: !Sub 'Watchy Platform Alerts - ${AWS::StackName}'
      Tags:
        - Key: Project
          Value: Watchy
        - Key: Component
          Value: Notifications
        - Key: StackName
          Value: !Ref AWS::StackName

  # Email Subscription to SNS Topic
  WatchyEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WatchyNotificationTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

  # Shared IAM Role for All Lambda Functions
  WatchySharedLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-WatchyPlatformRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WatchyPlatformPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudWatch Metrics for all SaaS apps
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
              # CloudWatch Logs with Watchy namespace
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*Watchy*'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/watchy/slack/*'
              # Parameter Store Access for API keys
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: 
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/watchy/api-keys'
              # SNS Publish for custom notifications
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref WatchyNotificationTopic

  # ===== SLACK MONITORING STACK =====

  # Slack Monitoring Stack
  SlackMonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub '${TemplateBaseUrl}/watchy-slack-monitoring.yaml'
      Parameters:
        SaasAppName: 'Slack'
        ApiUrl: !Ref SlackApiUrl
        MonitoringSchedule: !Ref MonitoringSchedule
        LogLevel: !Ref LogLevel
        TimeoutSeconds: !Ref TimeoutSeconds
        RetryAttempts: !Ref RetryAttempts
        ApiKeysParameter: !Ref ApiKeysParameter
        SharedLambdaRoleArn: !GetAtt WatchySharedLambdaRole.Arn
        NotificationTopicArn: !Ref WatchyNotificationTopic
        ParentStackName: !Ref AWS::StackName
        BinaryDistributionUrl: !Ref BinaryDistributionUrl
        BinaryName: 'watchy-slack-monitor'
      Tags:
        - Key: Project
          Value: Watchy
        - Key: SaasApp
          Value: Slack
        - Key: BinaryType
          Value: Nuitka
        - Key: ParentStack
          Value: !Ref AWS::StackName

Outputs:
  # ===== SHARED PLATFORM OUTPUTS =====
  ApiKeysParameter:
    Description: 'Parameter Store name for Slack API keys'
    Value: !Ref ApiKeysParameter
    Export:
      Name: !Sub '${AWS::StackName}-ApiKeysParameter'

  NotificationTopicArn:
    Description: 'ARN of the shared SNS topic for Slack monitoring alerts'
    Value: !Ref WatchyNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-NotificationTopic'

  SharedLambdaRoleArn:
    Description: 'ARN of the shared Lambda execution role for Slack monitoring'
    Value: !GetAtt WatchySharedLambdaRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-SharedLambdaRole'

  NotificationEmail:
    Description: 'Email address configured for platform notifications'
    Value: !Ref NotificationEmail

  # ===== SLACK MONITORING OUTPUT =====
  SlackMonitoringStackId:
    Description: 'Stack ID of the Slack monitoring nested stack'
    Value: !Ref SlackMonitoringStack

  # ===== PLATFORM SUMMARY =====
  PlatformVersion:
    Description: 'Watchy platform version'
    Value: '5.0.0-slack-only'

  BinaryDistributionUrl:
    Description: 'Base URL for Nuitka binary distribution'
    Value: !Ref BinaryDistributionUrl
